services:
  web:
    image: nginx:alpine
    volumes:
      - ./web1:/usr/share/nginx/html
    networks:
      - backend

  reverse_proxy:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web1
      - web2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
